/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.betaville.options;

import edu.poly.bxmc.betaville.net.InsecureClientManager;
import java.awt.Color;
import java.io.IOException;
import java.net.UnknownHostException;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbPreferences;

final class NetworkingPanel extends javax.swing.JPanel {

    private final NetworkingOptionsPanelController controller;

    NetworkingPanel(NetworkingOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverTypeButtonGroup = new javax.swing.ButtonGroup();
        serverAddressLabel = new javax.swing.JLabel();
        serverAddressField = new javax.swing.JTextField();
        javaServerRadioButton = new javax.swing.JRadioButton();
        webServiceRadioButton = new javax.swing.JRadioButton();
        serverTypeLabel = new javax.swing.JLabel();
        testServerConnectionButton = new javax.swing.JButton();
        testConnectionProgressBar = new javax.swing.JProgressBar();
        connectionStatusLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(serverAddressLabel, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.serverAddressLabel.text")); // NOI18N

        serverAddressField.setText(org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.serverAddressField.text")); // NOI18N
        serverAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverAddressFieldActionPerformed(evt);
            }
        });

        serverTypeButtonGroup.add(javaServerRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(javaServerRadioButton, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.javaServerRadioButton.text")); // NOI18N
        javaServerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaServerRadioButtonActionPerformed(evt);
            }
        });

        serverTypeButtonGroup.add(webServiceRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(webServiceRadioButton, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.webServiceRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(serverTypeLabel, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.serverTypeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(testServerConnectionButton, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.testServerConnectionButton.text")); // NOI18N
        testServerConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testServerConnectionButtonActionPerformed(evt);
            }
        });

        connectionStatusLabel.setForeground(new java.awt.Color(255, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(connectionStatusLabel, org.openide.util.NbBundle.getMessage(NetworkingPanel.class, "NetworkingPanel.connectionStatusLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverAddressLabel)
                            .addComponent(serverTypeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverAddressField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(javaServerRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(webServiceRadioButton)
                                .addGap(0, 220, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testServerConnectionButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(connectionStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(testConnectionProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverTypeLabel)
                    .addComponent(javaServerRadioButton)
                    .addComponent(webServiceRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverAddressLabel)
                    .addComponent(serverAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testServerConnectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testConnectionProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectionStatusLabel)
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serverAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverAddressFieldActionPerformed

    private void javaServerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaServerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_javaServerRadioButtonActionPerformed

    private void testServerConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testServerConnectionButtonActionPerformed
        try {
            testConnectionProgressBar.setValue(0);
            connectionStatusLabel.setForeground(Color.RED);
            connectionStatusLabel.setText("Establishing Connection");
            InsecureClientManager icm = new InsecureClientManager(null, serverAddressField.getText());
            testConnectionProgressBar.setValue(50);
            connectionStatusLabel.setForeground(Color.YELLOW);
            connectionStatusLabel.setText("Sending Request");
            long testCall = icm.getDesignVersion();
            testConnectionProgressBar.setValue(100);
            connectionStatusLabel.setForeground(Color.GREEN);
            connectionStatusLabel.setText("Test Successful");
            System.out.println("Server is running " + testCall);
            icm.close();
        } catch (UnknownHostException ex) {
            DialogDisplayer.getDefault().notifyLater(new NotifyDescriptor.Message("Could not connect to " + serverAddressField.getText()));
        } catch (IOException ex) {
            DialogDisplayer.getDefault().notifyLater(new NotifyDescriptor.Message("Error while communicating with " + serverAddressField.getText()));
        }
    }//GEN-LAST:event_testServerConnectionButtonActionPerformed

    void load() {
        javaServerRadioButton.setSelected(true);
        serverAddressField.setText(NbPreferences.forModule(NetworkingPanel.class).get("ServerAddress", "master.betaville.net"));
    }

    void store() {
        if(javaServerRadioButton.isSelected()) NbPreferences.forModule(NetworkingPanel.class).put("NetworkConnection", InsecureClientManager.class.getName());
        else NbPreferences.forModule(NetworkingPanel.class).put("NetworkConnection", "JSON CONNECTION CLASS");
        NbPreferences.forModule(NetworkingPanel.class).put("ServerAddress", serverAddressField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionStatusLabel;
    private javax.swing.JRadioButton javaServerRadioButton;
    private javax.swing.JTextField serverAddressField;
    private javax.swing.JLabel serverAddressLabel;
    private javax.swing.ButtonGroup serverTypeButtonGroup;
    private javax.swing.JLabel serverTypeLabel;
    private javax.swing.JProgressBar testConnectionProgressBar;
    private javax.swing.JButton testServerConnectionButton;
    private javax.swing.JRadioButton webServiceRadioButton;
    // End of variables declaration//GEN-END:variables
}
