/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.betaville.mapviewer.options;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import org.openide.util.NbPreferences;

final class ColorsPanel extends javax.swing.JPanel {

    private final ColorsOptionsPanelController controller;

    ColorsPanel(ColorsOptionsPanelController controller) {
	this.controller = controller;
	initComponents();
	// TODO listen to changes in form fields and call controller.changed()
	
	removeUnwantedChooserPanels(myLocationColorChooser);
	removeUnwantedChooserPanels(proposalsColorChooser);
	removeUnwantedChooserPanels(wormholesColorChooser);
    }
    
    /**
     * Removes unwanted color choosers from the color chooser panel
     * 
     * @param colorChooser 
     */
    private void removeUnwantedChooserPanels(JColorChooser colorChooser){
	for(int i=0; i<colorChooser.getChooserPanels().length; i++){
	    AbstractColorChooserPanel chooser = colorChooser.getChooserPanels()[i];
	    if(chooser.getClass().getName().contains("Swatch")){
		colorChooser.removeChooserPanel(chooser);
	    }
	    else if(chooser.getClass().getName().contains("HSB")){
		colorChooser.removeChooserPanel(chooser);
	    }
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        myLocationColorChooser = new javax.swing.JColorChooser();
        proposalsColorChooser = new javax.swing.JColorChooser();
        wormholesColorChooser = new javax.swing.JColorChooser();

        tabbedPane.addTab(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.myLocationColorChooser.TabConstraints.tabTitle"), myLocationColorChooser); // NOI18N
        tabbedPane.addTab(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.proposalsColorChooser.TabConstraints.tabTitle"), proposalsColorChooser); // NOI18N
        tabbedPane.addTab(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.wormholesColorChooser.TabConstraints.tabTitle"), wormholesColorChooser); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
	myLocationColorChooser.setColor(NbPreferences.forModule(ColorsPanel.class).getInt("myLocationColorChooser", Color.red.getRGB()));
	proposalsColorChooser.setColor(NbPreferences.forModule(ColorsPanel.class).getInt("proposalsColorChooser", Color.yellow.getRGB()));
	wormholesColorChooser.setColor(NbPreferences.forModule(ColorsPanel.class).getInt("wormholesColorChooser", Color.green.getRGB()));
    }

    void store() {
	NbPreferences.forModule(ColorsPanel.class).putInt("myLocationColorChooser", myLocationColorChooser.getColor().getRGB());
	NbPreferences.forModule(ColorsPanel.class).putInt("proposalsColorChooser", proposalsColorChooser.getColor().getRGB());
	NbPreferences.forModule(ColorsPanel.class).putInt("wormholesColorChooser", wormholesColorChooser.getColor().getRGB());
    }

    boolean valid() {
	// TODO check whether form is consistent and complete
	return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser myLocationColorChooser;
    private javax.swing.JColorChooser proposalsColorChooser;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JColorChooser wormholesColorChooser;
    // End of variables declaration//GEN-END:variables
}
